// <auto-generated />
namespace WenShenERP.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddCity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCity));
        
        string IMigrationMetadata.Id
        {
            get { return "201502270044286_AddCity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
